version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: ./Dockerfile.local
    image: xgboost-docker
    ports:
      - "8888:8888"
    volumes:
      - ./persist/ml-disk:/ml-disk

